"""Backward-compatible CLI entry point relying on modular command package."""

from __future__ import annotations

from . import config
from .client import WikiClient
from .commands import app, console
from .commands.extract import (
    DEFAULT_HEADING_PREFIX,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_SEARCH_LIMIT,
    DEFAULT_TIMEOUT,
    DEFAULT_TTS_AUDIO,
    DEFAULT_TTS_FILE,
    DEFAULT_TTS_FORMAT,
    DEFAULT_TTS_NORMALIZE,
    DEFAULT_TTS_SERVER,
    DEFAULT_TTS_VOICE,
    DEFAULT_VERBOSE,
    DEFAULT_YOLO,
    DEFAULTS,
    INFLECT_AVAILABLE,
    APIError,
    Args,
    DisambiguationError,
    NetworkError,
    NotFoundError,
    _collect_cli_overrides,
    _handle_search,
    _show_search_menu,
    extract,
    extract_wikipedia_text,
    make_tts_friendly,
    normalize_for_tts,
    sanitize_filename,
    write_text_file,
)

__all__ = [
    "app",
    "console",
    "Args",
    "extract",
    "extract_wikipedia_text",
    "sanitize_filename",
    "normalize_for_tts",
    "make_tts_friendly",
    "INFLECT_AVAILABLE",
    "write_text_file",
    "_handle_search",
    "_show_search_menu",
    "DEFAULTS",
    "DEFAULT_TIMEOUT",
    "DEFAULT_SEARCH_LIMIT",
    "DEFAULT_TTS_SERVER",
    "DEFAULT_TTS_VOICE",
    "DEFAULT_TTS_FORMAT",
    "DEFAULT_TTS_AUDIO",
    "DEFAULT_TTS_FILE",
    "DEFAULT_TTS_NORMALIZE",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_HEADING_PREFIX",
    "DEFAULT_VERBOSE",
    "DEFAULT_YOLO",
    "NetworkError",
    "APIError",
    "NotFoundError",
    "DisambiguationError",
    "_collect_cli_overrides",
    "config",
    "WikiClient",
]
